# Generated by Django 2.2.5 on 2019-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='本文')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
